import { Item, Match, Notification, User } from '../types';

export const mockCurrentUser: User = {
  id: 'u1',
  name: 'Jane Doe',
  studentId: 'STU10293',
  email: 'jane.doe@university.edu',
  role: 'student',
};

export const mockItems: Item[] = [
  {
    id: 'i1',
    userId: 'u1',
    type: 'lost',
    title: 'Apple AirPods Pro',
    category: 'Electronics',
    description: 'White AirPods Pro in a clear case. Left earbud has a small scratch.',
    brand: 'Apple',
    color: 'White',
    date: '2023-10-24',
    time: '14:30',
    location: 'Library',
    imageUrl: 'https://images.unsplash.com/photo-1606220838315-056192d5e927?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    createdAt: '2023-10-24T15:00:00Z',
  },
  {
    id: 'i2',
    userId: 'u2',
    type: 'found',
    title: 'White Wireless Earbuds',
    category: 'Electronics',
    description: 'Found a pair of white Apple earbuds near the 2nd floor study area.',
    brand: 'Apple',
    color: 'White',
    date: '2023-10-24',
    time: '15:00',
    location: 'Library',
    imageUrl: 'https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?auto=format&fit=crop&q=80&w=600',
    status: 'active',
    createdAt: '2023-10-24T15:30:00Z',
  },
  {
    id: 'i3',
    userId: 'u3',
    type: 'lost',
    title: 'Black HP Laptop',
    category: 'Electronics',
    description: 'HP Envy x360, 15 inch, black color. Has a sticker of a cat on the back.',
    brand: 'HP',
    color: 'Black',
    date: '2023-10-23',
    time: '10:00',
    location: 'Cafeteria',
    status: 'active',
    createdAt: '2023-10-23T11:00:00Z',
  },
  {
    id: 'i4',
    userId: 'u4',
    type: 'found',
    title: 'Blue Nike Backpack',
    category: 'Bags',
    description: 'Contains some notebook and a water bottle.',
    brand: 'Nike',
    color: 'Blue',
    date: '2023-10-22',
    time: '09:15',
    location: 'Sports Complex',
    status: 'active',
    createdAt: '2023-10-22T10:00:00Z',
  },
];

export const mockMatches: Match[] = [
  {
    id: 'm1',
    lostItemId: 'i1',
    foundItemId: 'i2',
    categoryScore: 100,
    locationScore: 100,
    timeScore: 90,
    descriptionScore: 92,
    colorScore: 100,
    brandScore: 100,
    finalScore: 93,
    status: 'pending',
    reasons: [
      'Same category (Electronics)',
      'Same campus location (Library)',
      'Reported within 30 minutes',
      'Similar description ("AirPods Pro", "Apple earbuds")',
      'Same color (White)',
    ],
    lostItem: mockItems[0],
    foundItem: mockItems[1],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    title: 'High Confidence Match!',
    message: 'A potential match was found for your lost AirPods.',
    isRead: false,
    type: 'match',
    createdAt: '2023-10-24T16:00:00Z',
    link: '/matches',
  },
  {
    id: 'n2',
    userId: 'u1',
    title: 'Claim Submitted',
    message: 'Your claim for "Blue Nike Backpack" was submitted to the finder.',
    isRead: true,
    type: 'claim',
    createdAt: '2023-10-23T09:00:00Z',
  },
];
